export type AppLanguage = 'en-US' | 'pt-BR';

/** @deprecated Use AppLanguage — kept as alias for API compatibility. */
export type OutputLanguage = AppLanguage;

export interface SummarizeRequest {
  url: string;
  language: AppLanguage;
}

export interface SummarizeResult {
  markdown: string;
}

export function parseAppLanguage(value: unknown): AppLanguage {
  return value === 'pt-BR' ? 'pt-BR' : 'en-US';
}

export function apiErrorMessage(
  language: AppLanguage,
  key: 'invalidUrl' | 'invalidYoutube' | 'summarizeFailed' | 'methodNotAllowed',
): string {
  const en = {
    invalidUrl: 'Invalid URL.',
    invalidYoutube: 'Enter a valid YouTube URL.',
    summarizeFailed: 'Failed to summarize the video.',
    methodNotAllowed: 'Method not allowed.',
  };
  const pt = {
    invalidUrl: 'URL inválida.',
    invalidYoutube: 'Informe um URL válido do YouTube.',
    summarizeFailed: 'Falha ao resumir o vídeo.',
    methodNotAllowed: 'Método não permitido.',
  };

  return (language === 'pt-BR' ? pt : en)[key];
}

/**
 * Stub for the future cloud AI summarization pipeline.
 * Returns sample Markdown so the UI can be developed end-to-end.
 */
export async function summarizeVideo(
  request: SummarizeRequest,
): Promise<SummarizeResult> {
  const { url, language } = request;

  // Simulate network latency for a more realistic UX during development.
  await new Promise((resolve) => setTimeout(resolve, 600));

  if (language === 'pt-BR') {
    return {
      markdown: [
        '# Resumo do Vídeo',
        '',
        `**Fonte:** ${url}`,
        '',
        '## Visão geral',
        '',
        'Este é um resumo **placeholder** gerado pelo Vid.md. O processamento via IA na nuvem substituirá este stub em uma versão futura.',
        '',
        '## Pontos principais',
        '',
        '- Cole um URL do YouTube e escolha o idioma do app',
        '- O app processará o vídeo via IA na nuvem',
        '- O resultado será retornado como Markdown formatado',
        '',
        '## Observações',
        '',
        '> O Vid.md exige conexão com a internet e é distribuído como aplicativo desktop portable.',
        '',
      ].join('\n'),
    };
  }

  return {
    markdown: [
      '# Video Summary',
      '',
      `**Source:** ${url}`,
      '',
      '## Overview',
      '',
      'This is a **placeholder** summary generated by Vid.md. Cloud AI processing will replace this stub in a future release.',
      '',
      '## Key Points',
      '',
      '- Paste a YouTube URL and choose your app language',
      '- The app will process the video via cloud AI',
      '- Results are returned as formatted Markdown',
      '',
      '## Notes',
      '',
      '> Vid.md requires an internet connection and ships as a portable desktop app.',
      '',
    ].join('\n'),
  };
}
